name: site sync

on:
  push:
    branches: [main]
    paths: [site/**]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: site
          git-user: czy88840616
          git-password: ${{ secrets.GH_TOKEN }}
          deployment-branch: gh-pages
